name: Jekyll site CI

on:
  push:
    branches:
      - master  # or main, depending on your default branch
  pull_request:
    branches:
      - master  # or main, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build --source app --destination app/_site --future

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        branch: gh-pages  # The branch where the site will be deployed
        folder: app/_site  # The directory where Jekyll builds the site
